### ISSUE TITLE
Native listener dropping concurrent requests on unix socket

### ISSUE THREAD

**Issue by kcd83** [xplicit/HyperFastCgi#37] opened 2015-07-29 01:49 UTC
I am seeing issues with Apache Bench at concurrency greater than 10 threads. I've recreated this on Ubuntu 14.04.1 LTS, mono 4.0.2 and nginx 1.4.6 to eliminate any quirks from our environment.

Native listener using unix sockets
```
ab -t60 -n 1500 -c 10 'http://10.100.125.94/admin/status'
Failed requests:        2
Non-2xx responses:      2
Requests per second:    665.51 [#/sec] (mean)

ab -t60 -n 1500 -c 30 'http://10.100.125.94/admin/status'
Failed requests:        534
Non-2xx responses:      534
Requests per second:    1595.88 [#/sec] (mean)

ab -t60 -n 1500 -c 100 'http://10.100.125.94/admin/status'
Failed requests:        547
Non-2xx responses:      955
Requests per second:    1831.00 [#/sec] (mean)
```
Running the managed code I can get currency of 100-200 without issue. There is a reduction in performance but it doesn't drop requests resulting in 502 responses from nginx.

Your blog showed you at least achieving 30 concurrent connections without issue. Did you see these issues?

**Comment by xplicit** [comment] 2015-07-29 03:54
Do you have the same issue if change unix sockets to sockets in config? What nginx log and hyperfastcgi logs contain? 

Maybe you've run into similar issue https://github.com/xplicit/HyperFastCgi/issues/33 
If you have similar it would be great if you provide reproducible test case, because I could not reproduce it yet.

**Comment by kcd83** [comment] 2015-07-29 22:14
Change to TCP sockets? No I do not see this issue over TCP.

I built this environment with the aim to make it easy to reproduce so yes I will get as much information as I can. 

#33 looks different but I will keep an eye out for that one also. On timeout getting a response from the application I get these, which is to be expected
```
libev.c:317: cmd_error():       Remote host disconnected from fd 14.
```

Regarding concurrent connections I get no errors from hyperfastcgi, in nginx I get
```
015/07/28 23:08:28 [error] 19666#0: *3061 connect() to unix:/tmp/hyperfastcgi.socket failed (11: Resource temporarily unavailable) while connecting to upstream,
```
With nginx debug on I get this
```
2015/07/29 21:52:43 [debug] 22517#0: *3005 http postpone filter "/admin/status?" 0000000002044CD8
2015/07/29 21:52:43 [debug] 22517#0: *3005 write old buf t:1 f:0 0000000002044A60, pos 0000000002044A60, size: 255 file: 0, size: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 write new buf t:1 f:0 0000000001FF5A90, pos 0000000001FF5B48, size: 151 file: 0, size: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 http write filter: l:0 f:0 s:406
2015/07/29 21:52:43 [debug] 22517#0: *3005 http copy filter: 0 "/admin/status?"
2015/07/29 21:52:43 [debug] 22517#0: *3005 pipe write downstream done
2015/07/29 21:52:43 [debug] 22517#0: *3005 event timer: 19, old: 1438206823225, new: 1438206823232
2015/07/29 21:52:43 [debug] 22517#0: *3005 http upstream exit: 0000000000000000
2015/07/29 21:52:43 [debug] 22517#0: *3005 finalize http upstream request: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 finalize http fastcgi request
2015/07/29 21:52:43 [debug] 22517#0: *3005 free rr peer 1 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 close http upstream connection: 19
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FF74E0, unused: 48
2015/07/29 21:52:43 [debug] 22517#0: *3005 event timer del: 19: 1438206823225
2015/07/29 21:52:43 [debug] 22517#0: *3005 reusable connection: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 http upstream temp fd: -1
2015/07/29 21:52:43 [debug] 22517#0: *3005 http output filter "/admin/status?"
2015/07/29 21:52:43 [debug] 22517#0: *3005 http copy filter: "/admin/status?"
2015/07/29 21:52:43 [debug] 22517#0: *3005 image filter
2015/07/29 21:52:43 [debug] 22517#0: *3005 xslt filter body
2015/07/29 21:52:43 [debug] 22517#0: *3005 http postpone filter "/admin/status?" 00007FFF932CB180
2015/07/29 21:52:43 [debug] 22517#0: *3005 write old buf t:1 f:0 0000000002044A60, pos 0000000002044A60, size: 255 file: 0, size: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 write old buf t:1 f:0 0000000001FF5A90, pos 0000000001FF5B48, size: 151 file: 0, size: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 write new buf t:0 f:0 0000000000000000, pos 0000000000000000, size: 0 file: 0, size: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 http write filter: l:1 f:0 s:406
2015/07/29 21:52:43 [debug] 22517#0: *3005 http write filter limit 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 writev: 406
2015/07/29 21:52:43 [debug] 22517#0: *3005 http write filter 0000000000000000
2015/07/29 21:52:43 [debug] 22517#0: *3005 http copy filter: 0 "/admin/status?"
2015/07/29 21:52:43 [debug] 22517#0: *3005 http finalize request: 0, "/admin/status?" a:1, c:1
2015/07/29 21:52:43 [debug] 22517#0: *3005 event timer add: 9: 5000:1438206768232
2015/07/29 21:52:43 [debug] 22517#0: *3005 http lingering close handler
2015/07/29 21:52:43 [debug] 22517#0: *3005 recv: fd:9 0 of 4096
2015/07/29 21:52:43 [debug] 22517#0: *3005 lingering read: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 http request count:1 blk:0
2015/07/29 21:52:43 [debug] 22517#0: *3005 http close request
2015/07/29 21:52:43 [debug] 22517#0: *3005 http log handler
2015/07/29 21:52:43 [debug] 22517#0: *3005 posix_memalign: 0000000001FFBF40:4096 @16
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FF5A90
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FF2A60, unused: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000002043E10, unused: 54
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FFBF40, unused: 3905
2015/07/29 21:52:43 [debug] 22517#0: *3005 close http connection: 9
2015/07/29 21:52:43 [debug] 22517#0: *3005 event timer del: 9: 1438206768232
2015/07/29 21:52:43 [debug] 22517#0: *3005 reusable connection: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FF70D0
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FEE520, unused: 0
2015/07/29 21:52:43 [debug] 22517#0: *3005 free: 0000000001FF6FC0, unused: 112
2015/07/29 21:52:43 [debug] 22517#0: *3002 post event 000000000201D130
2015/07/29 21:52:43 [debug] 22517#0: *3002 post event 0000000002030940
2015/07/29 21:52:43 [debug] 22517#0: *3002 delete posted event 0000000002030940
2015/07/29 21:52:43 [debug] 22517#0: *3002 http empty handler
2015/07/29 21:52:43 [debug] 22517#0: *3002 delete posted event 000000000201D130
2015/07/29 21:52:43 [debug] 22517#0: *3002 http lingering close handler
2015/07/29 21:52:43 [debug] 22517#0: *3002 recv: fd:14 -1 of 4096
2015/07/29 21:52:43 [info] 22517#0: *3002 recv() failed (104: Connection reset by peer) while sending to client, client: 10.100.124.147, server: , request: "GET /admin/status HTTP/1.0", upstream: "fastcgi://unix:/tmp/hyperfastcgi.socket", host: "10.100.125.94"
2015/07/29 21:52:43 [debug] 22517#0: *3002 lingering read: -1
2015/07/29 21:52:43 [debug] 22517#0: *3002 http request count:1 blk:0
2015/07/29 21:52:43 [debug] 22517#0: *3002 http close request
2015/07/29 21:52:43 [debug] 22517#0: *3002 http log handler
2015/07/29 21:52:43 [debug] 22517#0: *3002 posix_memalign: 0000000001FF5A90:4096 @16
2015/07/29 21:52:43 [debug] 22517#0: *3002 free: 000000000204A280
2015/07/29 21:52:43 [debug] 22517#0: *3002 free: 0000000001FF3A70, unused: 0
2015/07/29 21:52:43 [debug] 22517#0: *3002 free: 0000000001FF4A80, unused: 54
2015/07/29 21:52:43 [debug] 22517#0: *3002 free: 0000000001FF5A90, unused: 3905
2015/07/29 21:52:43 [debug] 22517#0: *3002 close http connection: 14
```
So it looks like the unix socket isn't buffering. What do you think?

**Comment by kcd83** [comment] 2015-07-29 23:14
Not sure if this is related to either issue but silly levels of concurrency crash HFC. I was trying to reproduce 33 and found this with one or two runs of the following
```
ab -r -n 50000 -c 1000 'http://10.100.125.94/admin/status'
```
For me errors only seem to go to console and not the log file. Not sure why these particular traces are empty.
```
libev.c:317: cmd_error():    Remote host disconnected from fd 26.
libev.c:317: cmd_error():       Remote host disconnected from fd 28.
libev.c:317: cmd_error():       Remote host disconnected from fd 24.
libev.c:317: cmd_error():       Remote host disconnected from fd 26.
libev.c:317: cmd_error():       Remote host disconnected from fd 24.
libev.c:317: cmd_error():       Remote host disconnected from fd 24.
libev.c:317: cmd_error():       Remote host disconnected from fd 34.
Stacktrace:


Native stacktrace:


```
It stops responding and I need to `kill -9` it, delete the unix socket then restart it.

I'm using
```
mono --debug /usr/lib/hyperfastcgi/4.0/HyperFastCgi.exe /config=/etc/hyperfastcgi/server.config /logfile=/var/log/hyperfastcgi.log /loglevels=Debug
```
And
```
<configuration>
  <server type="HyperFastCgi.ApplicationServers.SimpleApplicationServer">
    <host-factory>HyperFastCgi.HostFactories.SystemWebHostFactory</host-factory>
    <threads min-worker="40" max-worker="0" min-io="4" max-io="0" />
  </server>
  <listener type="HyperFastCgi.Listeners.NativeListener">
    <apphost-transport type="HyperFastCgi.Transports.NativeTransport"></apphost-transport>
    <protocol>Unix</protocol>
    <address>/tmp/hyperfastcgi.socket</address>
  </listener>
  <apphost type="HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost">
<!--    <log level="Debug" write-to-console="true" /> -->
<log level="All" />
    <add-trailing-slash>false</add-trailing-slash>
  </apphost>
  <web-applications>
    <web-application>
      <name>webapp</name>
      <vhost></vhost>
      <vport>80</vport>
      <vpath>/</vpath>
      <path>/usr/share/nginx/html/webapp</path>
    </web-application>
  </web-applications>
</configuration>
```
This is probably not much help, it doesn't appear relevant...

**Comment by kcd83** [comment] 2015-08-03 04:10
@xplicit have you ran apache bench against any of your setups?

**Comment by xplicit** [comment] 2015-08-03 16:02
I tried to catch the issue, but couldn't reproduce it. In your debug nginx log there a client disconnect, so it should not be a hfc error.

        2015/07/29 21:52:43 [info] 22517#0: *3002 recv() failed (104: Connection reset by peer) while sending to client, client: 10.100.124.147, server: , request: "GET /admin/status HTTP/1.0", upstream: "fastcgi://unix:/tmp/hyperfastcgi.socket", host: "10.100.125.94"
 
But information about how to reproduce #33 is very important. I tried to reproduce in my environment with my codebase, but have no luck to catch it. I even know what can cause this issue, but without reproducible test case can't fix it. Do you have a small test case which I can run in my environment to reproduce the issue?

**Comment by xplicit** [comment] 2016-05-24 11:16
Should be fixed via https://github.com/xplicit/HyperFastCgi/commit/aeadc0e130c43a979c2e986817c90c1a9bfb73b8

**Closed by xplicit** 2016-05-24 11:16 UTC
